import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import Image from 'next/image'

import UnderConstructionImage from '@public/under-construction.svg'

const Container = styled.div`
  padding: 0 2rem;
`

const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
`

const Title = styled.h1`
  color: #544af4;
  font-weight: 700;
  font-size: 45px;
  margin-right: 50px;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>Web site is building...</Title>
        <Image
          src={UnderConstructionImage}
          alt="under construction"
          width="500px"
          height="500px"
        />
      </Main>
    </Container>
  )
}

export default Home
